[package]
name = "vmail-lib"
version = "0.1.0"
authors = ["Armin Widegreen <armin.widegreen@gmail.com>"]

[dependencies]
diesel = { version = "1.2.0", features = ["mysql"] }
diesel-derive-enum = { version = "0.4", features = ["mysql"] }
dotenv = "0.10.0"
failure = "0.1"
failure_derive = "0.1"
